### ISSUE TITLE
Public Repository

### ISSUE THREAD

**Issue by benjaminbrumbaugh** [finkbeiner-lab/LBD-Analysis#1]
Hey @monika-ahirwar, Julia had some concerns about having public repositories for unpublished projects. Should this project be public?

Warmly,
Ben

**Comment by monika-ahirwar** [comment]
Hi, I have changed it to "Private" for now. The project is just started. It doesn't need to be Public as of now.

**Comment by benjaminbrumbaugh** [comment]
Thanks @monika-ahirwar!
